### ISSUE TITLE
Better  separation of stdout and stderr for `podman-hpc pull ...` 

### ISSUE THREAD

**Issue by wholtz** [NERSC/podman-hpc#56]
I'd like to see `podman-hpc pull ...` only output to stdout during a successful pull so that I can use it in a script like this:

```
podman-hpc pull docker.io/debian:bullseye > /dev/null
```

and only get output if there was a problem.

**Comment by lastephey** [comment]
After some debugging I traced this behavior back to Podman rather than podman-hpc. Podman sends the usual container pull output to stderr. Here I'm testing on my laptop:

```
(base) DOE-7616476:~ stephey$ podman pull quay.io/podman/hello:latest > /dev/null
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob sha256:32c07ec4961ddabfb3bb898fbbac172cad872e732a2ac5b8b8cc7e379a5aacff
Copying config sha256:c098961c7f4cf309b966502d01ec5a36cca74ab9385fb286c5aa07bf915cd9a6
Writing manifest to image destination
Storing signatures
(base) DOE-7616476:~ stephey$ 
```

Our podman-hpc design goal is to be a transparent wrapper on top of Podman, so we'll route the output the same way they do. You're welcome to open an issue with Podman and see what think about changing this behavior. 

I'll go ahead and close this.
